#!/bin/bash

if [[ -n "$2" ]]
then
	channel=$2
else
	case $HOSTNAME in
		*) channel=Master ;;
	esac
fi

case $1 in
	up)
		mpc volume +2
		;;
	down)
		mpc volume -2
		;;
	toggle)
		amixer set $channel toggle
		;;
	get)
		mpc volume | sed -r 's/^volume: ?([^%]+)%.*/\1/' | tr -d '\n'

		echo -n ' '

		amixer get $channel |
		sed -rn 's/.*\[([a-z]+)\]/\1/p' |
		head -1
		;;
	getchannel)
		echo $channel
		;;
esac
